#!/usr/bin/env python3
"""Build a scratch collector and test overflow recovery under growth failure.

Run from any directory: python3 tests/markstack.py [--output NEW_DIRECTORY]
Requires Linux, Python 3, CMake, and a C compiler with pthread and libdl support.
The source tree is never modified. No failure hook is installed in production.
The 64-bit typed-array payload is 216 MiB; each child has a 1 GiB address-space
limit and a 60-second timeout. Logs, exact injected source and JSON results are
retained, including on failure. These are correctness checks, not benchmarks.
"""

import argparse
import hashlib
import json
import os
from pathlib import Path
import resource
import shlex
import shutil
import subprocess
import tempfile


def replace_once(text, before, after):
    if text.count(before) != 1:
        raise RuntimeError("stale instrumentation pattern: " + repr(before))
    return text.replace(before, after, 1)


HOOKS = r"""
/* Diagnostic hooks: generated by tests/markstack.py in a scratch copy only. */
void
GC_recovery_test_arm(unsigned policy)
{
  LOCK();
  recovery_test_policy = policy;
  recovery_test_armed = TRUE;
  recovery_test_attempts = recovery_test_failures = recovery_test_overflows = 0;
  UNLOCK();
}

void
GC_recovery_test_snapshot(size_t *out)
{
  LOCK();
  out[0] = GC_mark_stack_size;
  out[1] = recovery_test_attempts;
  out[2] = recovery_test_failures;
  out[3] = recovery_test_overflows;
  out[4] = sizeof(mse);
  UNLOCK();
}

static mse *
recovery_test_allocate(size_t n)
{
  if (recovery_test_armed && GC_mark_stack != NULL && n > GC_mark_stack_size) {
    ++recovery_test_attempts;
    if (recovery_test_policy == 2
        || (recovery_test_policy == 1 && recovery_test_failures == 0)) {
      ++recovery_test_failures;
      return NULL;
    }
  }
  return (mse *)GC_scratch_alloc(n * sizeof(mse));
}

"""


def instrument(source):
    path = source / "mark.c"
    text = path.read_text()
    text = replace_once(
        text, '#include "private/gc_pmark.h"',
        '#include "private/gc_pmark.h"\n'
        'static GC_bool recovery_test_armed = FALSE;\n'
        'static unsigned recovery_test_policy;\n'
        'static size_t recovery_test_attempts, recovery_test_failures,\n'
        '              recovery_test_overflows;')
    text = replace_once(text, 'static void\nalloc_mark_stack(size_t n)\n{',
                        HOOKS + 'static void\nalloc_mark_stack(size_t n)\n{')
    text = replace_once(
        text, '  new_stack = (mse *)GC_scratch_alloc(n * sizeof(struct GC_ms_entry));',
        '  new_stack = recovery_test_allocate(n);')
    text = replace_once(
        text, '    GC_COND_LOG_PRINTF("No room to copy back mark stack\\n");',
        '    if (recovery_test_armed)\n'
        '      ++recovery_test_overflows; /* mark lock is held */\n'
        '    GC_COND_LOG_PRINTF("No room to copy back mark stack\\n");')
    path.write_text(text)


def run(command, log, **kwargs):
    with log.open("w") as stream:
        subprocess.run(command, stdout=stream, stderr=subprocess.STDOUT,
                       check=True, **kwargs)


def limits():
    resource.setrlimit(resource.RLIMIT_AS, (1024**3, 1024**3))
    resource.setrlimit(resource.RLIMIT_CORE, (0, 0))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, help="new directory for all artifacts")
    parser.add_argument("--source", type=Path, help="alternative collector source to test")
    args = parser.parse_args()
    script = Path(__file__).resolve()
    driver = script.with_name("markstack_overflow.c")
    resume_driver = script.with_name("markstack.c")
    original = args.source.resolve() if args.source else script.parent.parent
    output = args.output.resolve() if args.output else Path(
        tempfile.mkdtemp(prefix="bdwgc-markstack-"))
    if original == output or original in output.parents:
        raise ValueError("output must be outside the source tree")
    if args.output:
        output.mkdir(parents=True, exist_ok=False)
    print("Artifacts:", output, flush=True)
    source, build = output / "source", output / "build"
    shutil.copytree(original, source, ignore=shutil.ignore_patterns(
        ".git", "build*", "cmake-build*", "autom4te.cache", ".libs", ".deps",
        "__pycache__", "*.o", "*.lo", "*.a", "*.so", "*.so.*"))
    instrument(source)
    manifest = {"purpose": "correctness only", "cases": [],
                "source_directory": str(original),
                "build_environment": {key: os.environ[key] for key in
                                      ("CC", "CFLAGS", "LDFLAGS", "CMAKE_GENERATOR")
                                      if key in os.environ},
                "script_sha256": hashlib.sha256(script.read_bytes()).hexdigest(),
                "driver_sha256": hashlib.sha256(driver.read_bytes()).hexdigest(),
                "resume_driver_sha256": hashlib.sha256(
                    resume_driver.read_bytes()).hexdigest(),
                "source_sha256": hashlib.sha256(
                    (original / "mark.c").read_bytes()).hexdigest(),
                "instrumented_sha256": hashlib.sha256(
                    (source / "mark.c").read_bytes()).hexdigest()}
    manifest_path = output / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n")
    run(["cmake", "-S", str(source), "-B", str(build),
         "-DCMAKE_BUILD_TYPE=Release", "-DGC_BUILD_SHARED_LIBS=OFF",
         "-DBUILD_TESTING=OFF", "-Denable_threads=ON",
         "-Denable_parallel_mark=ON", "-Denable_gc_assertions=ON",
         "-Denable_werror=ON", "-Denable_large_config=ON"],
        output / "configure.log", timeout=120)
    manifest["cmake_compiler_configuration"] = [
        line for line in (build / "CMakeCache.txt").read_text().splitlines()
        if line.startswith(("CMAKE_C_COMPILER:", "CMAKE_C_COMPILER_ARG1:",
                            "CMAKE_C_FLAGS:", "CMAKE_C_FLAGS_RELEASE:"))]
    run(["cmake", "--build", str(build), "--target", "gc", "-j2"],
        output / "build.log", timeout=180)
    compiler = shlex.split(os.environ.get("CC") or "cc")
    manifest["driver_compiler"] = compiler
    manifest["driver_compiler_path"] = shutil.which(compiler[0])
    binary = output / "markstack-overflow"
    shutil.copyfile(driver, output / "driver.c")
    run(compiler + ["-O2", "-DGC_THREADS", "-Wall", "-Wextra", "-Werror",
                    "-I" + str(source / "include"),
                    str(output / "driver.c"),
                    str(build / "libgc.a"), "-pthread", "-ldl", "-o", str(binary)],
        output / "driver-build.log", timeout=60)
    resume_binary = output / "markstack-resume"
    shutil.copyfile(resume_driver, output / "resume-driver.c")
    run(compiler + ["-O2", "-DGC_THREADS", "-DGC_TEST_MARK_STACK_GROWTH",
                    "-Wall", "-Wextra", "-Werror", "-I" + str(source / "include"),
                    str(output / "resume-driver.c"), str(build / "libgc.a"),
                    "-pthread", "-ldl", "-o", str(resume_binary)],
        output / "resume-driver-build.log", timeout=60)
    env = {k: v for k, v in os.environ.items() if not k.startswith("GC_")}
    env["GC_PRINT_VERBOSE_STATS"] = "1"
    jobs = []
    for markers in (4, 1):
        for policy in (0, 1, 2):
            name = "markers%d-policy%d" % (markers, policy)
            jobs.append((name, markers, [str(binary), str(policy), str(markers)]))
        jobs.append(("resume-markers%d" % markers, markers,
                     [str(resume_binary)] + (["1"] if markers == 1 else [])))
    for name, markers, command in jobs:
        case = {"name": name, "command": command}
        manifest["cases"].append(case)
        env["GC_MARKERS"] = str(markers)
        try:
            with (output / (name + ".json")).open("w") as stdout, (
                    output / (name + ".stderr")).open("w") as stderr:
                proc = subprocess.run(command, env=env, stdout=stdout,
                                      stderr=stderr, timeout=60,
                                      preexec_fn=limits, check=False)
            case["returncode"] = proc.returncode
            if proc.returncode:
                raise RuntimeError(name + " failed; inspect stderr")
            case["result"] = json.loads((output / (name + ".json")).read_text())
            case["growth_failure_exercised"] = bool(
                case["result"]["injected_failures"])
            print(name, "passed", flush=True)
        except Exception as error:
            case["error"] = str(error)
            raise
        finally:
            manifest_path.write_text(json.dumps(manifest, indent=2) + "\n")
    print("Eight cases passed; serial cases may need no stack growth.")


if __name__ == "__main__":
    main()
